### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by lucifertrj** [AnonymouX47/matrix#2]
I noticed in the README file, the word **actually** is used multiple times. You can avoid it, so can I create a `Pull Request`. In addition, you have made a spelling mistake in the `Back-story` section. 
Actual Sentence: The project was actually `concieved` in the course of my "Journey through the Docs" 
Correct Sentence: The project was actually `conceived` in the course of my "Journey through the Docs" 
Thank You

**Comment by AnonymouX47** [comment]
Thanks :smiley:

I can't see any pull request though :thinking:...

**Comment by AnonymouX47** [comment]
Fixed!
Please, can you help to go through the changes?

Thanks.

**Comment by lucifertrj** [comment]
Looking good
